### PR TITLE
Remove reactHot from the devServer block

### LINKED ISSUE #56: Support for react-hot loader
Right now there is no support for the react-hot loader : https://github.com/gaearon/react-hot-loader

Basically what you need is the devServer enabled (already got the block for that) and the 'react-hot' loader before the 'babel-loader'.

Right now, I'm doing (first loader is babel in my case):
```js
module.exports.module.loaders[0].loaders.unshift('react-hot');
```

Is there a better way to do that in a non-hackish way?

### LINKED ISSUE #209: Deprecate devServer.reactHot()
1. There are several open issues and PRs: #56, #131.
2. It’s not generic, works only for React.
3. It’s only one of possible hot reload solutions for React.
4. None of them are actively maintained.
5. The need for it is overvalued in my opinion, default webpack hot reload is good enough.
6. **It was always broken in 1.0**

```diff
// test-app/webpack.config.babel.js
 const developmentConfig = () => group([
   sourceMaps(),
   devServer(),
+  devServer.reactHot(),
   devServer.proxy({
     '/api/*': { target: 'http://localhost:4000' }
   }),
```

→

```
ERROR in   Error: Child compilation failed:
  Module not found: Error: Can't resolve 'react-hot' in '/Users/sapegin/webpack-blocks/test-app'
  BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders.
                   You need to specify 'react-hot-loader' instead of 'react-hot',
                   see https://webpack.js.org/guides/migrating/#automatic-loader-module-name-extension-removed:
```

### PR DESCRIPTION
**Pull request by vlad-zhukov**
Fixes #209 
Closes #56, Closes #131

### CODE REVIEW

**Comment by sapegin** [comment]
Are you on Gitter by the way? Join or [chat](https://gitter.im/webpack-blocks) ;-)

**Comment by andywer** [comment]
Any reason not to merge yet? 😉

**Comment by sapegin** [comment]
@andywer Waiting for your review I guess ;-)

**Comment by andywer** [comment]
Ahh, my bad. I thought I had already approved!

**Comment by vlad-zhukov** [comment]
@sapegin you merged with no PR message and issues were not closed

**Comment by sapegin** [comment]
@vlad-zhukov That’s because GitHub closes issues only when code is in master.

**Pull request merged**
