### PR TITLE
Fix a skipped test in sample-app

### PR DESCRIPTION
**Pull request by vlad-zhukov**
As requested in #236 moving it in a separate PR.

### CODE REVIEW

**Comment by andywer** [comment]
Can you please merge the current `master` into the feature branch? I hope that fixes the build.

**Comment by vlad-zhukov** [comment]
I did earlier today, the typescript test is not failing anymore, but this test keep failing on Node 6 with a weird error. I couldn't reproduce it locally so far, will try look into it in the next few days.

**Comment by sapegin** [comment]
Could it be because Node 6 doesn’t support async/await?

**Comment by andywer** [comment]
@sapegin No, AVA transpiles test code on the fly by default.

**Comment by sapegin** [comment]
Why they do it? Where they get a Babel config to do that? ;-|

**Comment by sapegin** [comment]
Have found that in their docs. Another reason I like Jest more ;-£

**Comment by andywer** [comment]
I really like it, actually. Provides handy defaults, but allows you to disable or customize transpiling. And you can specify different babel transforms to be applied to the test code and the tested code :)

**Comment by andywer** [comment]
Closing for now.

**Pull request closed without merging**
