### PR TITLE
completed add dll plugins

### PR DESCRIPTION
**Pull request by nndung179**
I added **setDllPlugin** in webpack packages. If it is ok, I will update document

### CODE REVIEW

**Comment by eXon** [comment]
It's great to have DLLs but it's better when you can reference them ;)

You probably should add a core block for `DllReferencePlugin`. Looking forward to using it 👍

**Comment by andywer** [comment]
Hey guys! Interesting to see that the DLL functionality is such a hot feature.

But the proposed `setDllPlugin` function doesn't make it any easier to use it, I think. Is `setDllPlugin(x)` so much more readable than `addPlugins([ new webpack.DllPlugin(x) ])`?

(Feel free to share your opinion anytime if you feel differently about this! 😉)

Using the test app to demonstrate how the DllPlugin can be used seems like a good idea on first glance, but it also makes it more complicated. There is another webpack config file, another `script` in the `package.json` and so it doesn't feel as light-weight anymore.

I would suggest we provide a separate test app for the DLL functionality.

**Comment by andywer** [comment]
Or even better: I don't know if you got time for this, but it might be really cool to write a short blog post / tutorial (maybe on medium.com) about why and how to use the DllPlugin and provide an easy to use and easy to understand configuration like this one here.

It might even live in a separate examples repository and we just link there.

Or maybe we can somehow make it simpler to use the DLL feature...

**Comment by andywer** [comment]
Just recognized this is the follow-up of #16.

And I proposed exactly this, now I am not satisfied. Sorry man! 🙈😅

I guess I expected the util function to simplify the DllPlugin's options some more...

Sorry for the inconvenience! I appreciate your efforts.

**Comment by nndung179** [comment]
I will try another way. Just figured it new way to do it. You are totally right about how easy to use this feature :)

**Comment by nndung179** [comment]
Hi @andywer. I am making a function allow return dll configs. And I cannot think about how to run it without npm script. Any suggestion?

**Comment by andywer** [comment]
Hey @nndung179!
Anything new here or can I close the PR for now?

**Comment by nndung179** [comment]
I think PR should br closed. I will get back another time

**Comment by andywer** [comment]
Ok 👍

And thx for the quick reply :)

**Pull request closed without merging**
