### PR TITLE
use object spread

### PR DESCRIPTION
**Pull request by pravdomil**
see diff

### CODE REVIEW

**Comment by dmitmel** [comment]
Object rest spread was added in [Node 8](https://node.green/#ES2018-features-object-rest-spread-properties-object-spread-properties), but the minimal version of Node which webpack-blocks supports is 6th.

**Comment by pravdomil** [comment]
ok

**Comment by pravdomil** [comment]
btw: node 6 is only maintenance mode right now

https://github.com/nodejs/Release#release-schedule

**Comment by dmitmel** [comment]
Yes, but it's still [the most popular](https://nodesource.com/node-by-numbers) version of Node.

**Comment by pravdomil** [comment]
didn't know that, thanks

**Pull request closed without merging**
