### PR TITLE
Add resolve block (1.0)

### PR DESCRIPTION
**Pull request by diegohaz**
Related to #152 and #159

### CODE REVIEW

**Comment by andywer** [comment]
Thanks, @diegohaz :)

I just got one request: Removing `resolveAlias` from the README might be ok for 1.0, but it might make sense to leave the `resolveAlias` code in there for a little longer and just mark it as deprecated.

**Comment by andywer** [comment]
Btw, are you currently using 0.4 or 1.0-alpha?

**Comment by diegohaz** [comment]
I'm using 0.4

What's the approach you use to deprecate things? `console.warn`? Will do that later today.

**Comment by andywer** [comment]
Add a `@deprecated` to the jsdoc block above the function and... a `console.warn()` makes sense :)

**Comment by andywer** [comment]
But maybe we should list the possible properties `alias`, `modules`, ...

**Comment by diegohaz** [comment]
Done.

Enhanced examples and updated webpack documentation url (we need to update it on other blocks).
https://webpack.js.org/configuration/resolve/

**Comment by andywer** [comment]
Good job, @diegohaz. Thanks!

I think the `// import Utility from 'Utilities/utility'` comment is quite hard to understand, but that's just a minor thing. Maybe better `` // resolve `import 'Utilities/utility'` to correct path ``?

But that's really just a minor thing :)

**Pull request merged**
