### PR TITLE
Implement `defineConstants`

### LINKED ISSUE #17: Add a nice way to define constants
It would be great to have at the core level of webpack-blocks a way to define constants within the code. Right now, we could do that using the DefinePlugin but I think it deserves a nicer way.

Here is my proposal:

```js
const { createConfig, defineConstant } = require('@webpack-blocks/webpack')

module.exports = createConfig([
  defineConstant('process.env.NODE_ENV', process.env.NODE_ENV),
  defineConstant('__API__URL', process.env.API_URL),
  // ...
])
```

And it would be transformed by:

```js
new webpack.DefinePlugin({
  'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV),
  '__API_URL__', JSON.stringify(process.env.API_URL)
})
```

We might want to stack them instead of doing it with a single plugin. I don't know if it will be possible the way things are built with webpack-blocks.

Or maybe it could be a defineConstants that takes more than a single one.

What do you think? I can make a PR if you want to experiment with it.

### PR DESCRIPTION
**Pull request by andywer**
Now that we have got `pre`/`post` hooks, `context` and `group()` it is easy to implement `defineConstants`.

Resolves #17.

### CODE REVIEW

**Comment by eXon** [comment]
That's awesome! It's exactly what I had in mind. 

One thing I'm still wondering though. Because it is called `defineConstants` and not `replaceCode`, maybe the value you want to define should be stringified automatically don't you think?

You would be able to do:
```js
defineConstants({
    DEV: process.env.NODE_ENV !== 'production'
})
```

The `JSON.stringify` should be implicit in my mind. I don't think this should be used as a search&replace within your code for anything. I think it would cover 99% of the use case and make the usage better.

**Comment by andywer** [comment]
@eXon Excellent point! :)

I actually did forget to `JSON.stringify()` the values quite a few times in the past...

Will add that 👍👍

**Comment by andywer** [comment]
Constants' values are now automatically `JSON.stringify()`-ed! (see the [commit](https://github.com/andywer/webpack-blocks/pull/43/commits/886b5d3488585d39ba91320fcd3d452e009665b9))

**Comment by eXon** [comment]
This is perfect 👍

**Pull request merged**
