### PR TITLE
Update docs

### LINKED ISSUE #91: Add testing/setup documentation for contributors
## Package linking / testing before publishing

- `lerna bootstrap`
- Point out that `lerna bootstrap` is run automatically on `postinstall` (on Travis CI, too)
- `npm link`

## Testing concept

Types of tests:
- Unit tests
- Integration tests
- End-to-end tests

(What they reside, where they occur and when to write which one(s))

## Common pitfalls

- e2e tests: Copy `dependencies` of blocks to test into the `devDependencies` of `webpack`/`webpack2`

### PR DESCRIPTION
**Pull request by andywer**
- Added testing docs
- Added table of content to main readme and "How to write a block"

Resolves #91

### CODE REVIEW

**Comment by sapegin** [comment]
Do you write TOCs manually? I was thinking about generating them ;-)

**Comment by andywer** [comment]
I would prefer generation as well. How would you generate them? :)

**Comment by sapegin** [comment]
With [markdown-magic](https://github.com/DavidWells/markdown-magic) for example. But I haven’t tried it yet.

**Comment by andywer** [comment]
We should embrace recursive composition 👉
bildschirmfoto 2017-05-08 um 18 47 18

**Comment by andywer** [comment]
Any reasons not to merge this? 😉

**Pull request merged**
