### PR TITLE
Add NamedModulesPlugin when HotReloading is active

### PR DESCRIPTION
**Pull request by bkonkle**
This is *very* handy for debugging. 😀

### CODE REVIEW

**Comment by andywer** [comment]
Very good point! Thanks, @bkonkle :)

Just one concern: This is webpack 2 only, right?

**Comment by andywer** [comment]
Poking 👉 @bkonkle

**Comment by sapegin** [comment]
@andywer Should we merge this? 1.0 will work only with webpack 2 anyway.

**Comment by andywer** [comment]
Good point, @sapegin. Will rebase it on the 1.0 release branch later today.

**Pull request closed without merging**
