### PR TITLE
Make webpack a peer dependency, make webpack 3 compatible

### LINKED ISSUE #167: Migrate V1.0 to webpack 3
Webpack 3 was just released: https://github.com/webpack/webpack/releases/tag/v3.0.0
Only a few internal breaking changes so some plugins might be affected.

The big plus is scope hoisting like Rollup which increases initial paint and reduces bundle size

Would be nice to try

### PR DESCRIPTION
**Pull request by andywer**
Fixes #167

### CODE REVIEW

**Comment by Vlad-Zhukov** [comment]
Hello, what do you think about also removing webpack from the exports?

https://github.com/andywer/webpack-blocks/blob/release/1.0/packages/webpack/index.js#L18

**Comment by andywer** [comment]
Could probably be removed. Are there any strong feelings to remove it?

**Comment by Vlad-Zhukov** [comment]
Just a common sense.

**Comment by andywer** [comment]
I agree, but will fix it in a separate PR.

**Comment by andywer** [comment]
See #170

**Pull request merged**
