### PR TITLE
Pass typescript options via query string

### PR DESCRIPTION
**Pull request by jvanbruegge**
This allows you to pass options not only via tsconfig.json but also via webpack.config.js
I would need this for https://github.com/cyclejs-community/create-cycle-app/issues/103

### CODE REVIEW

**Comment by jvanbruegge** [comment]
I tested it locally and it works as expected

**Comment by andywer** [comment]
Good point. And as always thanks for the PR :)

But `tsconfig` and `compiler` options will now be passed as JSON options and via `TsConfigPathsPlugin`. Maybe it doesn't do any harm, but doesn't seem completely right either. Maybe separate the TsConfigPathsPlugin options from the loader options in the beginning?

**Comment by jvanbruegge** [comment]
I missunderstood the plugin, this is better now

**Comment by andywer** [comment]
Ok, now I am confused ^^
I can't find any `advancedPath` option on https://github.com/s-panferov/awesome-typescript-loader#loader-options

**Comment by jvanbruegge** [comment]
yes, because normally you would either add the plugin or not, the option just handles inclusion

**Comment by andywer** [comment]
Hmm, I like the proposed change in general, but I don't like having an additional custom option for utility purposes only. Maybe `options.paths` for `tsconfig` and `compiler`, the rest of `options` becomes loader options.

What do you say?

**Comment by jvanbruegge** [comment]
the loader needs the compiler and tsconfig too

**Comment by jvanbruegge** [comment]
i never used this feature (and i guess noone else too), so this never surfaced

**Comment by andywer** [comment]
But what is the `TsConfigPathsPlugin` good for if we have to pass the paths to the loader anyway?

Just recognized you were the autor of the block, so in case of doubt I tend to trust what you say 😉
But it still seems a little strange.

**Comment by jvanbruegge** [comment]
Im not completely sure either, the docs dont say why

**Comment by andywer** [comment]
Maybe it's worth opening an issue at the awesome-typescript-loader's repo?

**Comment by jvanbruegge** [comment]
yes i can do that.

**Comment by jvanbruegge** [comment]
There is already one, but it seems I use it right now

**Comment by andywer** [comment]
How about dropping the `options.advancedPaths` and go back to the `options.tsconfig || options.compiler` condition for the `TsConfigPathsPlugin` if we need it plus the complete JSON config?

(Especially since `@param {boolean} [options.advancedPath] See https://github.com/s-panferov/awesome-typescript-loader#loader-options` seems misleading and the documentation for `compiler` & `tsconfig` has been dropped)

The rest looks fine to me :)

**Comment by jvanbruegge** [comment]
I finally understood what the plugin is for. We can have it active all the time. It only affects people configuring it in the tsconfig.json. Thats why it needs the path. I will remove the check

**Comment by jvanbruegge** [comment]
Should I remove the unit test? It's actually quite pointless

**Comment by andywer** [comment]
Nice! Yes, I think it's safe to remove the unit tests. End-to-end tests are way more reliable for testing blocks. Poking #91...

But adding a comment explaining why we need the `TsConfigPathsPlugin` and why it's fine to feed it with `null`/`undefined` would be helpful.

**Comment by jvanbruegge** [comment]
Can we merge this?

**Comment by andywer** [comment]
Of course 👌

**Comment by andywer** [comment]
Published as `@webpack-blocks/typescript v0.4.1`

**Pull request merged**
