### PR TITLE
Webpack is no longer exported from webpack-blocks package

### LINKED ISSUE #207: Issue with the webpack blocks exports
Hi, I'm trying to set up a project using the release 1.0 branch, and I encountered some issues I wasn't able to resolve, here is the error stack. 
```
module.js:487
    throw err;
    ^

Error: Cannot find module 'webpack/lib/Chunk'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/mf/Code/accurapp/packages/webpack-preset-accurapp/node_modules/@webpack-blocks/extract-text/node_modules/extract-text-webpack-plugin/index.js:9:13)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```
I think it's an issue with the `extract-text-webpack-plugin` version, and probably related to #190, but I'm not using the `extract-text` package in my config.

Anyway, if you want to check out the config I'm working on [here it is](https://github.com/accurat/accurapp/blob/webpack-updates/packages/webpack-preset-accurapp/index.js), to replicate that issue I just ran `node index.js`.

Instead, when testing the config in the complete build process, this error pops up:

```
TypeError: Cannot read property 'DefinePlugin' of undefined
    at accuPreset (/Users/mf/Code/accurapp/test-app/node_modules/webpack-preset-accurapp/index.js:67:18)
    at Object.<anonymous> (/Users/accurat_mf/Code/accurapp/test-app/webpack.config.js:2:18)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at readWebpackConfig (/Users/accurat_mf/Code/accurapp/test-app/node_modules/accurapp-scripts/scripts/_utils.js:60:10)
    at Object.<anonymous> (/Users/accurat_mf/Code/accurapp/test-app/node_modules/accurapp-scripts/scripts/build.js:13:16)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```
It's telling me the variable `webpack` I require from webpack-blocks is undefined.

Feel free to ask any question about our usage of webpack blocks, might be useful some feedback, to test the configuration there is a `yarn create-test-app` command in the root.

### PR DESCRIPTION
**Pull request by sapegin**
Closes #207.

### CODE REVIEW

**Comment by sapegin** [comment]
How about `context.webpack`? Is it still available?

**Comment by andywer** [comment]
Yes, [`context.webpack` is still there](https://github.com/andywer/webpack-blocks/blob/8b768c6d0a5f905b3338bcb6a1be9afff6c2f173/packages/webpack/index.js#L45).

**Comment by sapegin** [comment]
Do we need it there? ;-)

**Comment by andywer** [comment]
Probably not, but not sure either. And I can't possibly tell if it's not being used somewhere right now (consider 3rd-party blocks as well), so I wouldn't touch that now.

**Comment by sapegin** [comment]
Later it maybe too late ;-)

**Comment by andywer** [comment]
Hmm. Might be easier to unit-test, though, if you use `context.webpack.FooPlugin` instead of `require('webpack').FooPlugin`.

**Comment by sapegin** [comment]
I think it’s *just* easier :-) Instead of a need to remember that webpack is available from the `context` and guessing what’s the difference with `require('webpack') and what is “webpack instance”, just use require it yourself.

**Comment by andywer** [comment]
Just pointing out that it might be useful for at least one use case.
But sure, require()-ing it manually is less magic / easier to understand.

**Comment by sapegin** [comment]
Haha, I thought you mean `require('webpack')` is easier for tests because in my opinion it is ;-)

**Comment by andywer** [comment]
I suggest we merge that now and discuss `context.webpack` separately, because the changes proposed here are fine (no discussion).

**Comment by sapegin** [comment]
Sounds good ;-)

**Pull request merged**
