### PR TITLE
v0.3 docs

### PR DESCRIPTION
**Pull request by andywer**
Updated the README, added an update note for the soon-to-be-released v0.3 (a.k.a. christmas release 🎄) and added a whole new documentation file on how to create blocks.

The actual features have been introduced by #33 (thanks @eXon!). You can preview the changes of this PR [here](https://github.com/andywer/webpack-blocks/tree/feature/v0.3-docs).

Feedback of any kind is very welcome 😉

Poking @eXon @andreiglingeanu

### CODE REVIEW

**Comment by eXon** [comment]
This is a great starting point. What's look weird to me is it is a mix of an API docs and a guide docs. Maybe we should split it between API.md and multiple small guides with clear and precise intend? By doing so it will be easier to generate a doc with GitBook or something like that.

**Comment by andywer** [comment]
Do you mean the README.md, BLOCK-CREATION.md or both?

Splitting API docs and guides seems like a good idea, but I think the README has got to cover both to some degree. Unless we keep the README minimalistic and just link to the other docs... 🤔

**Comment by andywer** [comment]
Added a quote of Dan Abramov to the readme. What do you think, @eXon?

**Comment by andreiglingeanu** [comment]
Looks great!

I like this way of composing configs a lot. Can you tell me, in two words, how the block specification is coupled with webpack? Will I be able to use same API for composing other types of configs?

As far as I know, the return value of blocks are merged with `webpack-merge` (and you are still in doubt if that's the right way to go), right?

**Comment by andywer** [comment]
@andreiglingeanu Actually the core API isn't coupled to webpack at all, besides `webpack-merge`. And yes, I am still not sure if the smart merge of webpack-merge is the best way to go (#34).

Basically the webpack-blocks approach of - let's call it - "functional configuration" could be applied to pretty much everything. I already use it for another use case as well ([flux-capacitor-boot](https://github.com/flux-capacitor/flux-capacitor/tree/master/packages/flux-capacitor-boot)).

For composing large and complicated data structures (like the webpack config) which you cannot make much simpler I would use that approach any time. If you are actually writing your own API and think about applying it there it might be worth considering rather functional code design patterns for your API itself, like Observables (👉 keeping it functional and complexity low from the beginning, instead of fixing it later using something webpack-blockish).

Why are you asking? 😉

**Comment by eXon** [comment]
@andywer I mean the README.md. I feel like it focus too much on how things are working rather than answering the question from a user experience.

I like how [react-router](https://github.com/reacttraining/react-router) has a docs folder focusing on one thing you might be trying to achieve, an examples folder and a very light readme just to get things started.

[Redux](https://github.com/reactjs/redux) is also doing the same thing and it generates a great Website using GitBook.

Maybe this should be in a separate issue, it might be out of scope for just documenting v0.3.0

**Comment by andreiglingeanu** [comment]
@andywer I have composable task builder for `gulp`, which includes handling multiple webpack entries (and some [dynamic](https://github.com/Creative-Themes/build-process/blob/f9aae907ab5b6efa97dd590ea93b3b2e0f9b1fa5/webpack.config.js#L20-L76) ones). I use in multiple internal projects of mine and I really like to keep it flexible enough to be able to handle complex situations. I'd also like to be able to quickly bootstrap a new project and get it running in no time.

This builder basically is just a function that receives `gulp` as an argument and assigns tasks to it (`gulp` itself is just a proxied [`Orchestrator`](https://github.com/robrich/orchestrator#1-get-a-reference) instance). The way I attach those tasks is configurable and current configuration API is a mess. That's why I was looking for possible ways of enforcing a structure over it. I'll maybe introduce some basic building blocks like - `webpack`, `sass` and a couple of other regular build tasks I use frequently.


Damn, I'll maybe switch away from handling sass with `gulp` and just proceed with ExtractText when I need files to be saved separately from the `.js` bundle. But I didn't liked the idea to keep one more server running (webpack HMR) just to be able to receive live CSS updates in browser - I don't use HMR for my JS (or I didn't bothered to configure it properly :)).

Thank you for pointing out the fact that you are using this architecture approach (yeah, let's name it _functional configuration_) not just for `webpack-blocks`. I'll take a more closer look at it.

> keeping it functional and complexity low from the beginning, instead of fixing it later using something webpack-blockish

That's a very good point but, sadly, it is too late :(

**Comment by andywer** [comment]
@eXon Pretty good point... Now that we have got presets we might also just provide a preset shipping basic pre-configured babel and dev-server config, plus setting `process.env.NODE_ENV`.

So we might end up with a good part of Create React App's features, but in a composable way.

But my personal goal for this week is shipping `v0.3` before christmas. We could probably release it today if we want, but I still try to get the webpack-2 stuff into `0.3` as well :)

On the other hand... If it already includes webpack-2, we could call it `v1.0` just as well 😅

**Comment by andywer** [comment]
@eXon Sorry, I lost focus. You are right about "explaining how to do stuff with it" vs. "explaining how it does stuff". But I also agree on postponing it a little longer.

**Comment by andywer** [comment]
@andreiglingeanu Not quite sure why you need gulp if use webpack, but I suppose you have got your reasons :)

> It really was simple from the beginning - but I started to add options in a hacky way so that I achieve my needs quickly.

Yeah, that's what usually happens if you go the data-driven configuration way. If it comforts you: I can easily imagine that the webpack creators experienced quite the same issue in webpack's early days just as well 😉

**Pull request merged**
