### PR TITLE
Change default devtool to cheap-module-eval-source-map

### PR DESCRIPTION
**Pull request by pravdomil**
Because they provide same level of detail as `cheap-module-source-map` but they are faster in rebuild.

see https://webpack.js.org/configuration/devtool

### CODE REVIEW

**Comment by vlad-zhukov** [comment]
Nice catch, thanks! Could you please point it to the `release-2.0` branch instead of the `master`? (See #264 for reference.) And after that you'd also need to make sure tests pass.

**Comment by dmitmel** [comment]
@pravdomil I have a local copy of webpack-blocks so I can make a PR towards your fork with the required changes to snapshots.

**Comment by pravdomil** [comment]
@dmitmel great

**Comment by pravdomil** [comment]
> All checks have passed

**Comment by pravdomil** [comment]
I have deleted the original repo so I have to open new PR https://github.com/andywer/webpack-blocks/pull/285

**Pull request merged**
