### PR TITLE
Fix validation error with default uglify options

### PR DESCRIPTION
**Pull request by jvanbruegge**
When running a webpack config with the default options the build fails due to a validation error.

### CODE REVIEW

**Comment by sapegin** [comment]
Did they change something? 

https://github.com/webpack-contrib/uglifyjs-webpack-plugin#parallel

**Comment by jvanbruegge** [comment]
I dont think so, but the validation is not throwing an error

**Comment by sapegin** [comment]
Then if boolean for `parallel` option is incorrect we should send a PR to uglifyjs-webpack-plugin too.

**Comment by sapegin** [comment]
Yup, it should work:

https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/ee1663991b37f243a65d0ee69e37169e6e113943/src/uglify/index.js#L19-L21

**Comment by sapegin** [comment]
https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/139

**Comment by sapegin** [comment]
They’ve made a breaking change without any change logs, the correct settings are:

```
parallel: true,
cache: true,
```

**Comment by sapegin** [comment]
We should also lock the uglifyjs-webpack-plugin version in package.json.

**Comment by andywer** [comment]
Thx for investigating, @sapegin! 👍

**Comment by sapegin** [comment]
Now the question is: why the CI is failing?

**Comment by sapegin** [comment]
@andywer Any ideas?

**Comment by jvanbruegge** [comment]
No idea

**Comment by andywer** [comment]
@sapegin Don't know. Just restarted the failed build. Maybe some issue with node 6 vs. node 8.

**Comment by andywer** [comment]
An end-to-end test fails and maybe lerna swallows the error message.

**Comment by vlad-zhukov** [comment]
v1.0 was released

**Comment by andywer** [comment]
@vlad-zhukov Thx for the hint! 🙂

**Comment by andywer** [comment]
@jvanbruegge Can we just merge jvanbruegge/webpack-blocks#1? Then we should be able to merge this PR, release a new version of the uglify block and the other PT builds should become green as well :)

Would just be good if someone would have a look at my changes in jvanbruegge/webpack-blocks#1

**Comment by jvanbruegge** [comment]
Done

**Comment by andywer** [comment]
Will merge and release this evening :)

**Comment by andywer** [comment]
@vlad-zhukov 
>  I'd put the sample app into an examples folder and add it to lerna

How would you add it to lerna?

**Comment by vlad-zhukov** [comment]
@andywer [using the `packages` field](https://github.com/lerna/lerna#lernajson). I can submit a PR tomorrow.

**Comment by andywer** [comment]
@vlad-zhukov Ahh, alright. Good idea 👍

**Comment by andywer** [comment]
Published as `@webpack-blocks/uglify v1.1.0` & `webpack-blocks v1.0.0-rc.2` 🚀

**Pull request merged**
