### PR TITLE
Add a note about enabling hot reload

### PR DESCRIPTION
**Pull request by sapegin**

### CODE REVIEW

**Comment by andywer** [comment]
Good point, we need to address this. Still not sure, though, if we should use `react-hot-loader/webpack` or not.

**Comment by sapegin** [comment]
This is not about react-hot-loader just a basic webpack hot reload.

I think we should deprecate react-hot-loader and suggest users to create a third-party block.

**Comment by andywer** [comment]
Yeah, I agree on that. Was just referring to that because you chose a react hot reloading example 😉

**Comment by sapegin** [comment]
Yeah, because that’s a sample from my article and I’ve spent some time figuring out why it’s not working ;-)

**Comment by sapegin** [comment]
Do you want me to change anything here?

**Comment by andywer** [comment]
No, it's fine. Thx for reminding me :)

**Pull request merged**
