### PR TITLE
Added less block

### PR DESCRIPTION
**Pull request by Veikedo**
Added less block.
@kirill-konshin please test the block since I can't do it for a while.

### CODE REVIEW

**Comment by kirill-konshin** [comment]
Most importantly, the plugin does not work with Extract Text block, the output is just a string in JS bundle, SASS block does not work with it as well: #115.

Second, adding `sourceMap: true` to options produces error:
```
ERROR in ./~/css-loader?sourceMap!./~/less-loader?{"sourceMap":true}!./src/styles.less
Module build failed: TypeError: Path must be a string. Received undefined
```

**Comment by kirill-konshin** [comment]
Regarding the issue with `extractText` (#115) - documentation needs to be fixed.

**Comment by kirill-konshin** [comment]
This can be merged now since #116 has been fixed with #119.

**Comment by andywer** [comment]
Can you please check which linting issues make the build fail?

I will have a look at it myself, but right now I am busy working on the new API (#125).

**Comment by sapegin** [comment]
@andywer Do we want this in the core? I’d suggest to keep it as a third-party block since Less is way less popular that Sass.

**Comment by andywer** [comment]
Since nobody complained recently... I suppose it would make more sense to keep it as a 3rd-party block.
@kirill-konshin Are you interested in publishing it as your own repo/package?

**Comment by kirill-konshin** [comment]
I don't mind, just tell me how should I take over it.

P.S. I personally think that official support of Less is also a very nice to have thing along with official support of Sass. I use both actually, in different projects, because of different advantages.

**Comment by andywer** [comment]
Sure and I would appreciate it a lot if you would find some time to publish a `less` block under your own flag, nevertheless. It is still important and I will tweet about it.

We will advertise your block here, too, don't worry. I know I keep saying this for far too long, but we shall have an official list of 3rd-party blocks in a prominent place soon :)

**Comment by sapegin** [comment]
I could find around 6 third-party blocks on npm, so Readme could be a good place to start — I can send a PR.

**Comment by andywer** [comment]
Sure, let's just put it into the readme for now!

**Comment by sapegin** [comment]
@kirill-konshin Are you still interested in making a third-party block for Less?

**Comment by kirill-konshin** [comment]
Yes. I will publish it today/tomorrow. What's the naming convention?

**Comment by sapegin** [comment]
`webpack-blocks-less` would work — https://github.com/andywer/webpack-blocks/tree/release/1.0#third-party-blocks

**Comment by kirill-konshin** [comment]
https://www.npmjs.com/package/webpack-blocks-less published almost as is based on this PR. Contributions are welcome. This PR can be closed, but please, add a reference to README then...

**Comment by sapegin** [comment]
@kirill-konshin Awesome! You need to update an example in readme and repository field in package.json — they still point to webpack-blocks repo.

And feel free to send a PR to add a link to our Readme ;-)

**Pull request closed without merging**
