### PR TITLE
webpack-blocks convenience package (for 1.0)

### PR DESCRIPTION
**Pull request by andywer**
Introduces the "webpack-blocks" convenience package that wraps the following packages:

* @webpack-blocks/assets
* @webpack-blocks/babel6
* @webpack-blocks/dev-server
* @webpack-blocks/extract-text
* @webpack-blocks/postcss
* @webpack-blocks/typescript
* @webpack-blocks/webpack

Packages in the repo not contained in this package:

* @webpack-blocks/elm
* @webpack-blocks/sass
* @webpack-blocks/tslint

Please tell if you are ok with the included packages or not! 😉
I am especially unsure about the `sass` package, since it's frequently used, but also takes some noticeable time to install.

Also:
Bumped all package versions to `v1.0.0-alpha`, so we can publish an alpha release.

@jvanbruegge @eXon @sapegin #134

### CODE REVIEW

**Comment by sapegin** [comment]
I’d extract TypeScript and PostCSS too for consistency.

**Comment by jvanbruegge** [comment]
I would include them as they are used very frequently. And unlike sass, they install fast

**Comment by andywer** [comment]
@sapegin Can you explain your thought a little further?

I think PostCSS is important, since everyone using css or css modules will want to use at least the autoprefixer, I guess.

TypeScript is a tricky one. But I thought that including both might still be ok and will make it easy to use for both React as well as Angular as well as most other current framework's users (see [comment](https://github.com/andywer/webpack-blocks/issues/134#issuecomment-298836377))

**Comment by sapegin** [comment]
I mean if you including TypeScript but excluding much more popular Sass it looks strange and inconsistent.

**Comment by jvanbruegge** [comment]
Me personally would include Sass, but I'm not sure how many people use it

**Comment by stevenjlho** [comment]
I think Sass is more popular than Typescript. For me, i want to add Sass package.

**Comment by andywer** [comment]
Good points. Fortunately, we don't have to guess!

The sass-loader is in fact installed [~500k times per week](https://npm-stat.com/charts.html?package=sass-loader) (comparison: the super universal style-loader is installed [~800k times](https://npm-stat.com/charts.html?package=style-loader)).

So you are right, it is not just very popular, but extremely popular. We should add it, even it slows down the `npm install`.

**Comment by andywer** [comment]
There we go. Added `sass` to `webpack-blocks` package as well 😉

**Comment by andywer** [comment]
Do you want to have more time to review it or should I merge it and publish the alpha?

**Comment by sapegin** [comment]
:shipit:

**Comment by jvanbruegge** [comment]
for me it is ready to go

**Comment by andywer** [comment]
Published under the `@next` tag. Check out [this comment in the 1.0 issue](https://github.com/andywer/webpack-blocks/issues/134#issuecomment-299906813) for further information.

**Pull request merged**
