### PR TITLE
Proposal for pre/post hooks & context object & group()

### PR DESCRIPTION
**Pull request by eXon**
This is what I am proposing we could do for pre/post hooks. You can take a look at the dev-server for an example.

We could hook ourself before processing the blocks so that we can change the fileTypes or activate the sourceMaps before createConfig is called.

We can also hook ourself at the end so we can do something once we have the whole config (like the dev-server).

I also changed the `fileTypes` parameter by `context`. It is a big breaking change but I think it's for the best.

Let me know what you think! (the doc is still missing for now)

### CODE REVIEW

**Comment by eXon** [comment]
I'm not sure about the additional config I added to `invokeConfigSetters`. It looks like I cannot use `baseConfig` to chain the calls so I added `initialConfig`. Not sure it's the best solution.

**Comment by eXon** [comment]
It looks like there is a weird bug when merging the entry points. Both entry points are merged as `['./test.js', 'entry]` instead of there respective entry points. I have no clue why.

**Comment by andywer** [comment]
Hey @eXon. Thanks for your case study on the pre/post-processing hooks feature.

I noticed some more issues about it though:
- Branch seems to be based on `improve/normalize-entry-points` and wants to be merged back into it. This is not so good. Feature branches should fork from `master`/`develop` and be merged back, so we don't get a mess there :)
- The global hooks arrays in the `core` block: Now the blocks would all need to require the `core` block and it will break as soon as there are multiple `@webpack-blocks/core` in `node_modules` (may happen if different blocks require different versions of `core`)

I like the idea of the `context` object and passing it as first parameter to the blocks, though 👍

**Comment by andywer** [comment]
My suggestion for the pre/post-hooks:

Implementation in a block:
```js
function myBlock () {
  const setConfig = () => ({
    entry: './foo'
  })
  return Object.assign(setConfig, {
    pre (context) {},
    post (context, config) {}
  })
}
```

So it still returns a function as it always did, but we can also add `pre`/`post` properties to the function (since a function also is an object).

**Comment by andywer** [comment]
Proposal: I am going to merge the `normalize-entry-points` soon, that's gonna be version `0.2.0`. We might bundle the `context` object and `pre`/`post` hooks feature together to a version `0.3.0`.

Btw: This is a PR for #25. Please mention the issue when opening a PR related to an issue 😉

**Comment by eXon** [comment]
I'll change the PR target to master as soon as the branch is merged. I needed the change for testing with the dev-server but I didn't wanted to include those changes when looking at the diff.

I though about the same solution but what I don't like about it is we don't want to include the pre/post function more than once even though we might have a block multiple times.

The solution to this might be to switch the dependency to @webpack-blocks/core to a peerDependency. This would make sure even though you might have different versions on different blocks they would all use the same.

If you read about [peer dependencies](https://nodejs.org/en/blog/npm/peer-dependencies/), you'll quickly realized it is exactly for this kind of use case. The blocks are plugins and we want to make sure we include only once `@webpack-blocks/core` and respect a version requirement.

In my opinion it makes things a lot simplier. What do you think?

**Comment by andywer** [comment]
The need to require a webpack-blocks package from within the blocks seems like an anti-pattern to me. And calling those functions outside of the block function as well.

We can make it a peer-dependency, but it is still not elegant and we introduce a footgun there. It will complicate the dependencies and as soon as there are multiple versions of the same package it will fall apart (a single `npm link` during development might already achieve that).

But: The objection that we might call the `pre`/`post` handlers multiple times is a good concern 👍👍

Got to find an elegant solution for that, the rest should be easy...

**Comment by eXon** [comment]
@andywer We might be able to detect the pre/post hook is already there by comparing the function with toString() (not a big fan but would be effective)

It would be much simplier to write a pre/post hook and it would only run them if you used the block at least once. I'll try what it looks like.

**Comment by eXon** [comment]
Here is an example of a possible post hook:

```js
function devServer (options, entry) {
  if (options && (typeof options === 'string' || Array.isArray(options))) {
    entry = options
    options = {}
  } else {
    entry = entry || 'webpack/hot/only-dev-server'
  }

  entry = Array.isArray(entry) ? entry : [ entry ]

  const devServerBlock = (context) => {
    context.devServer = true
    return {}
  }

  devServerBlock.post = (context, config) => {
    if (!context.devServer) {
      return {}
    }

    return {
      devServer: Object.assign({
        hot: true,
        historyApiFallback: true,
        inline: true
      }, options),
      entry: addDevEntryToAll(config.entry || {}, entry),
      plugins: [
        new webpack.HotModuleReplacementPlugin()
      ]
    }
  }

  return devServerBlock
}
```

The hook should be executed only once because it compares the function as a string. We can't use the reference because each of them will be different.

**Comment by eXon** [comment]
If we choose to get this way, we'll need to make sure when we do #24 that we also set the subBlocks while merging them just like I did within `env()`

**Comment by andywer** [comment]
@eXon Sorry for delayed response, but you know how it is in the time before x-mas... 🙈

Yeah, that should do the trick. I guess you don't like the `return Object.assign(() => ({}), { pre, post })` syntax? ^^ Do you think it's harder to read?

There might be one alternative to `function.toString()`: We could also define the `pre`/`post` methods outside the block function, so the references to the hook functions are constant. But it might be hard to track down the error if you create the `pre`/`post` functions dynamically.

**Comment by eXon** [comment]
Just changed what you proposed and I think you'll like it better. In that example I keep no anonymous function for the sake of clarity.

```js
function devServer (options, entry) {
  if (options && (typeof options === 'string' || Array.isArray(options))) {
    entry = options
    options = {}
  } else {
    entry = entry || 'webpack/hot/only-dev-server'
  }

  entry = Array.isArray(entry) ? entry : [ entry ]

  const devServerBlock = (context) => {
    context.devServer = { entry }

    return {
      devServer: Object.assign({
        hot: true,
        historyApiFallback: true,
        inline: true
      }, options)
    }
  }

  return Object.assign(devServerBlock, { post: devServerPost })
}

function devServerPost (context, config) {
  if (!context.devServer) {
    return {}
  }

  return {
    entry: addDevEntryToAll(config.entry || {}, context.devServer.entry),
    plugins: [
      new webpack.HotModuleReplacementPlugin()
    ]
  }
}
```

**Comment by andywer** [comment]
👍

Just one suggestion: `devServerPost` as a name feels not ideal. How about `postConfig`?
I think the function name does not need to contain `devServer`, since there is only dev-server stuff in the file :)

**Comment by eXon** [comment]
I think it makes sense. 

If we can agree on that, I'm not sure where this should be documenting. This looks like an advanced feature when creating a block so I'm not sure if this should be within the main readme.

**Comment by andywer** [comment]
@eXon I guess that's the right moment to turn the "How does a block look like from the inside?" paragraph of the README into a new separate markdown file: "How to write a webpack block" :)

I will have more time tomorrow and the following days. Gonna look into that 😉

**Comment by eXon** [comment]
I just changed the target to master. I'll let you start the new docs folder.

Do you want to include the doc within this PR?

**Comment by andywer** [comment]
Yes, I think at least some basic documentation should be part of this PR. Will look into it this weekend!

The PR is approaching its merge... :)

**Comment by andywer** [comment]
Btw: Just realized that the probably most important part of integrating this PR will be the context-object breaking change.

It might be good to increase the version number of **all** blocks to `0.3.0` and put a big note in the top part of the README that you either have to upgrade all blocks to `>= 0.3.0` or use all blocks in a version `< 0.3.0`.

**Comment by andywer** [comment]
@exon I still have some smaller code change proposals (I think we don't need the `subSetters`). Do you mind if I just push to your feature branch? (I think GitHub allows me to, but not completely sure)

**Comment by eXon** [comment]
@andywer I'm not sure how we can get rid of subSetters. It keep track of the setters when you use `env()` or potentially latter `groups()`. Otherwise, there is no way to know what are the pre/post hooks within those grouped blocks.

**Comment by andywer** [comment]
@eXon Actually it should be quite easy. Right now (before the PR) `group(a, b) = combineSetters(a, b)`.

Right now in the PR it is `group(a, b) = Object.assign(combineSetters(a, b), { subSetters: [a, b] })`

But this means we now have two types of blocks. Blocks with `subSetters` and blocks without. And since uniformity is key to composability, I propose:

`group(a, b) = Object.assign(combineSetters(a, b), { pre: combineHooks(a.pre, b.pre), post: combineHooks(a.post, b.post) })`

(I know, there is no `group()` yet, but it is just the 90% functionality of `env()` we are talking about here :) )

I think it's easy to see if I just adapt the code.

**Comment by eXon** [comment]
I added you as a collaborator on my fork so I guess you have access to change it now

**Comment by eXon** [comment]
@andywer I though about the same thing at first but it becomes a lot harder to remove duplicate hooks that way.

**Comment by andywer** [comment]
@eXon Damn it. You are right.

But... I think I know another approach that might do the trick: Let's allow `pre` and `post` to be an array, so `group(a, b) = Object.assign(combineSetters(a, b), { pre: [ a.pre, b.pre ], post: [ a.post, b.post ] })` (slightly simplified).

It is slightly unelegant, because `pre`/`post` may now be either a function or an array of functions. But... There is no need for a new property, so the block data model can stay small and concise.

**Comment by eXon** [comment]
@andywer I think I found a pretty elegant solution with your idea. Even more simplier than what we have and easily pluggable on the future `groupBlocks()` function :)

**Comment by andywer** [comment]
@eXon 👍

I am right in the middle of implementing the same thing (incl. the unit tests to make sure it does what it's supposed to do).

I guess I will finish my work and then try to take your's + my tests.

**Comment by eXon** [comment]
I was hoping you wasn't doing it at the same time xD My code is lacking tests for sure.

**Comment by andywer** [comment]
Updated the feature branch / PR. And the headline 😅

Added unit tests and changed the code of `core/src/index.js` a bit. *Feel free to review what I did!*
Also implemented the `group()` method for creating presets, since it's < 10 lines of code and we now got everything we need to implement it.

**Comment by andywer** [comment]
Btw: `config` is not passed to the `pre` hooks anymore, since the pre hooks run before configuration stuff and cannot change it either 😉 So we enforce pre hooks to really just modify the context.

**Comment by andywer** [comment]
Looking at `test: context.fileTypes('text/css'),` and wondering if it should rather be `test: context.fileType('text/css')` (fileType, without the 's') 🤔

Then it would also be `context.fileType.add('foo/bar', /something/)`. But that seems ok :)

**Comment by andywer** [comment]
@eXon Let's decide on `context.fileTypes` vs. `context.fileType` and merge that beast of a PR then.

Subsequent steps:
- Open PR for new / updated documentation
- Implement `defineConstants` (see #17)
- Version bump: 0.3 (a.k.a. the christmas release 🎄)
- (Port changes to webpack2 branch)

**Comment by eXon** [comment]
@andywer I think plurial should be used if there is a good reason behind only. `context.fileType()` is slightly better.

**Comment by andywer** [comment]
@eXon Alright. Will look into that tomorrow morning. Thinking about doing that in a separate PR after merging this one :)

We are approaching the christmas release! 🎉

**Comment by andreiglingeanu** [comment]
Sounds great!

**Pull request merged**
