### PR TITLE
Fix default exclude on windows

### PR DESCRIPTION
**Pull request by jvanbruegge**
Im using this block for a boilerplate and because of windows' use of backslash as directory seperator this regex fails

### CODE REVIEW

**Comment by jvanbruegge** [comment]
when will it be on npm?

**Comment by andywer** [comment]
Will merge #109 as soon as the tests have passed and then bump & publish the updated babel6 block. ETA 10 minutes 😉

**Comment by andywer** [comment]
Forget about the 10m. It's published! 😄

**Comment by jvanbruegge** [comment]
sweet

**Pull request merged**
