### PR TITLE
Add package keywords for npm discoverability

### PR DESCRIPTION
**Pull request by adamdicarlo**
Hi @andywer! Webpack Blocks is such an awesome idea. I've found it a bit difficult to find the various available blocks on npmjs.com though, so here are some keywords! :)

### CODE REVIEW

**Comment by andywer** [comment]
Thanks, @adamdicarlo! 👍

There is a list of the available blocks in the [README](https://github.com/andywer/webpack-blocks#available-webpack-blocks), though. Is it because you rather like to use `npm search` or is the list in the README not placed prominently enough?

**Comment by andywer** [comment]
(Changes will be visible on npm after the next release)

**Comment by adamdicarlo** [comment]
Hmm, true! I did see that, although wasn't focusing enough to realize it's supposed to be an exhaustive list, I think. Though I probably would have also wondered what else might be out there that wasn't listed in this README. And there are a few at least -- I sent a PR over to `webpack-blocks-purescript` to add a keyword there too, and that's published (the author also added the keywords to his couple other packages and published 'em!). Great to have multiple avenues of discovery!

I came to know about webpack-blocks via the [awesome webpack](https://github.com/webpack-contrib/awesome-webpack) list btw!

**Comment by adamdicarlo** [comment]
Oh right, I remember—part of the reason I was on npmjs.com after looking at the readme: I wanted to see the package pages to see how popular the packages were.

**Comment by andywer** [comment]
Interesting! :)

Yeah, I saw the ecliptic webpack-blocks packages as well. I might contact them. Already thought about a minimalistic website listing all available blocks, but I have got more important things to handle right now, so maybe later.

Just hard to tell the popularity, since npm does still not support download stats for scoped packages...

**Comment by adamdicarlo** [comment]
Oh, I didn't know that about scoped packages! Hope they get that working soon.

**Comment by andywer** [comment]
Here is the issue, in case you want to track it yourself 😉

npm/registry#59

**Pull request merged**
