### PR TITLE
Port to webpack 2.0 config style

### PR DESCRIPTION
**Pull request by aaronjensen**
~~This is still WIP until we have a solution for https://github.com/andywer/webpack-blocks/issues/34#issuecomment-282934444~~

This is based on #128 and should be good to go once that is merged.

### CODE REVIEW

**Comment by andywer** [comment]
Any idea why the build fails? It's two end-to-end tests that fail (`babel/postcss/extract-text` and `sass/extract-text`).

My first guess was that it's somehow related to `extract-text`, since it's the only e2e tests that use it, but I cannot find the source of the problem...

**Comment by aaronjensen** [comment]
@andywer yes, the problem is https://github.com/andywer/webpack-blocks/issues/34#issuecomment-282934444 / https://github.com/survivejs/webpack-merge/pull/70

Basically, the output of `ExtractTextPlugin.extract()`'s order is not respected because of the merge.

**Comment by andywer** [comment]
Ahh, I see. It's because you already did the `module.loaders` => `module.rules` migration, despite the PR's title...

Might have been better to do that in a separate PR, so we could have merged the removal of the webpack@1 blocks.

**Comment by andywer** [comment]
I can try to fork your branch and `git revert` the `module.loaders => module.rules` commits for now.

**Comment by aaronjensen** [comment]
Yeah, the title is misleading. This is basically the upgrade to webpack 2 branch. The branch could probably be rebased to include only the "Remove *" and "Move *" commits if you want just the removal

**Comment by andywer** [comment]
That would be really good to get working (green build) base for further modifications.

I just tried reverting the other commits, but I still get that strange `Error: self is not defined` error in the e2e tests.

**Comment by aaronjensen** [comment]
I'll open a new branch/pull, give me a sec

**Comment by aaronjensen** [comment]
I retitled and rebased this onto the newly created #127

**Comment by andywer** [comment]
Cool!

I started working on the new API. In fact I already implemented the new API in the core, but am still updating the tests and the blocks.

I put the updated core code into a gist, in case you need to try it urgently: https://gist.github.com/andywer/d892d0eb39d2de7f6ebfcdf5b7e9b248

**Comment by aaronjensen** [comment]
Looks good so far, I think. Give me a ping when it's ready to merge and I'd be happy to take a look at it.

**Comment by andywer** [comment]
Quick thought:

When I see this code
```js
/**
 * @param {object} proxyRoutes    { <path>: <target URL> }
 * @return {Function}
 * @see http://webpack.github.io/docs/webpack-dev-server.html#proxy
 */
function proxy (proxyRoutes) {
  return (context, helpers) => helpers.merge({
    devServer: {
      proxy: proxyRoutes
    }
  })
}
```

I think it should probably not be `helpers`, but `util`. What do you think? Should be consistent, though.

**Comment by aaronjensen** [comment]
Yeah, util is fine. I prefer destructuring if available of course.

**Comment by andywer** [comment]
Me too, but we don't transpile most blocks, so... Let's wait for node 4 to die 😅

**Comment by aaronjensen** [comment]
@andywer I rebased this onto #128. It should be good to go once that's merged.

**Comment by aaronjensen** [comment]
@andywer rebased again, good to merge I think.

**Comment by andywer** [comment]
Cool! 👍😊

Did you test it in a real-world scenario yet / did you try it together with your custom blocks?
(If not it's not so bad, end-to-end tests are green. Just curious 😉)

**Comment by aaronjensen** [comment]
Nope, I haven't had a chance yet.

**Pull request merged**
