### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by marcofugaro**
This PR upgrades these main dependencies: 

- webpack
- webpack-dev-server
- css-loader
- style-loader
- sass-loader
- babel-loader
- eslint-loader
- url-loader
- file-loader
- node-sass

And these minor dependencies:
- lodash
- webpack-merge
- glob-to-regexp

Along with it, some packages require a newer version of node, since the dependencies require it as well. I think we should do a mayor for this reason.

The loader that changed their api are `css-loader` and `sass-loader`, I updated README, test and code to reflect these changes. Also I removed some deprecated options from test and examples (`hmr` for style-loader and `minimize` for css-loader)

Finally, I did not touch `@webpack-blocks/typescript` and `@webpack-blocks/uglify` since those are bigger tasks.

### CODE REVIEW

**Comment by marcofugaro** [comment]
CI is breaking on node 8 as expected.

**Comment by vlad-zhukov** [comment]
👍 if CI is green

**Comment by marcofugaro** [comment]
Alright, updated the travis node version and fixed the conflict.

**Comment by andywer** [comment]
Great stuff! And sorry for the hiccup…

Would anyone like to approve the PR? I can also force-merge it, but I guess that’s what brought us here in the first place…

**Comment by marcofugaro** [comment]
@andywer could you release a new version when you have time? 🙏

**Comment by andywer** [comment]
@marcofugaro Released as v2.1.0 🚀

**Pull request merged**
